export const ADD_INGR_IN_CONSTRUCTOR = "ADD_INGR_IN_CONSTRUCTOR";
export const ADD_BUN_IN_CONSTRUCTOR = "ADD_BUN_IN_CONSTRUCTOR";
export const DEL_INGR_CONSTRUCTOR = "DEL_INGR_CONSTRUCTOR";
export const MOVE_INGR_CONSTRUCTOR = "MOVE_INGR_CONSTRUCTOR";
export const CALC_TOTAL_PRICE = "CALC_TOTAL_PRICE";
