export const WS_CONNECTION_START_FEED = "WS_CONNECTION_START_FEED";
export const WS_CONNECTION_SUCCESS_FEED = "WS_CONNECTION_SUCCESS_FEED";
export const WS_CONNECTION_ERROR_FEED = "WS_CONNECTION_ERROR_FEED";
export const WS_CONNECTION_CLOSED_FEED = "WS_CONNECTION_CLOSED_FEED";
export const WS_GET_MESSAGE_FEED = "WS_GET_MESSAGE_FEED";
export const WS_CLEAR_STATE_FEED = "WS_CLEAR_STATE_FEED";
export const WS_CONNECTION_OPEN_FEED = "WS_CONNECTION_OPEN_FEED";
