export const SET_INGREDIENT_IN_MODAL = "SET_INGREDIENT_IN_MODAL";
export const DEL_INGREDIENT_IN_MODAL = "DEL_INGREDIENT_IN_MODAL";
export const TOGGLE_MODAL_INGR = "TOGGAL_MODAL_INGR";
export const TOGGLE_MODAL_ORDER = "TOGGAL_MODAL_ORDER";
