export const WS_USER_ORDER_GET_MESSAGE = "WS_USER_ORDER_GET_MESSAGE";
export const WS_USER_ORDER_CONNECTION_START = "WS_USER_ORDER_CONNECTION_START";
export const WS_USER_ORDER_CONNECTION_OPEN = "WS_USER_ORDER_CONNECTION_OPEN";
export const WS_USER_ORDER_CONNECTION_CLOSED =
  "WS_USER_ORDER_CONNECTION_CLOSED";
